workflows:
  ios-release:
    name: Courier App Release
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Apple Key" # <--- Проверьте, что в Codemagic ключ называется именно так
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: restify.CourierApp
    scripts:
      - name: Сборка приложения (Build IPA)
        script: |
          # Скрипт сам найдет проект в папке CourierAppios16
          PROJECT_PATH=$(find . -name "*.xcodeproj" | head -n 1)
          xcode-project build-ipa \
            --project "$PROJECT_PATH" \
            --scheme "CourierApp"
    artifacts:
      - build/ios/ipa/*.ipa
